--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022. 02. 05. 17:43:49
-- Server version: 10.4.11
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE autosiskola;

--
-- Drop table `elmeleti_oraszamok`
--
DROP TABLE IF EXISTS elmeleti_oraszamok;

--
-- Drop table `gyakorlati_oraszamok`
--
DROP TABLE IF EXISTS gyakorlati_oraszamok;

--
-- Drop table `kategoriak`
--
DROP TABLE IF EXISTS kategoriak;

--
-- Drop table `oktatok`
--
DROP TABLE IF EXISTS oktatok;

--
-- Drop table `oktato_jarmuvek`
--
DROP TABLE IF EXISTS oktato_jarmuvek;

--
-- Drop table `tanulok`
--
DROP TABLE IF EXISTS tanulok;

--
-- Set default database
--
USE autosiskola;

--
-- Create table `tanulok`
--
CREATE TABLE tanulok (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Vezeteknev VARCHAR(255) DEFAULT NULL,
  Keresztnev VARCHAR(255) DEFAULT NULL,
  Harmadiknev VARCHAR(255) DEFAULT NULL,
  Anyja_neve VARCHAR(255) DEFAULT NULL,
  Szuletesi_orszag VARCHAR(255) DEFAULT NULL,
  Szuletesi_hely VARCHAR(255) DEFAULT NULL,
  Szuletesi_ido DATE DEFAULT NULL,
  Allampolgarsag VARCHAR(255) DEFAULT NULL,
  Lakcim_irsz INT(11) DEFAULT NULL,
  Lakcim_telepules VARCHAR(255) DEFAULT NULL,
  Lakcim_utca VARCHAR(255) DEFAULT NULL,
  Lakcim_hazszam INT(11) DEFAULT NULL,
  Lakcim_egyeb VARCHAR(255) DEFAULT NULL,
  Ertesitesi_cim_irsz INT(11) DEFAULT NULL,
  Ertesitesi_cim_telepules VARCHAR(255) DEFAULT NULL,
  Ertesitesi_cim_utca VARCHAR(255) DEFAULT NULL,
  Ertesitesi_cim_hazszam INT(11) DEFAULT NULL,
  Ertesitesi_cim_egyeb VARCHAR(255) DEFAULT NULL,
  Email VARCHAR(50) DEFAULT NULL,
  Telefonszam VARCHAR(255) DEFAULT NULL,
  Szemelyiigazolvany_szama VARCHAR(255) DEFAULT NULL,
  Szemelyiigazolvany_ervenyesseg DATE DEFAULT NULL,
  Szemelyiigazolvany_kiallito_orszag VARCHAR(255) DEFAULT NULL,
  Jogositvany_szama VARCHAR(255) DEFAULT NULL,
  Jogositvany_ervenyesseg DATE DEFAULT NULL,
  Egeszsegugyi_csoportkod INT(6) DEFAULT NULL,
  Jogositvany_kiallito_orszag VARCHAR(255) DEFAULT NULL,
  Gondviselo_Email VARCHAR(50) DEFAULT NULL,
  Gondviselo_Telefonszam VARCHAR(255) DEFAULT NULL,
  Valasztott_kategoria INT(11) DEFAULT NULL,
  Valasztott_gyakorlati_oktato INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `oktato_jarmuvek`
--
CREATE TABLE oktato_jarmuvek (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Oktatoi_engedely_szama VARCHAR(255) DEFAULT NULL,
  Oktatoi_engedely_ervenyessege DATE DEFAULT NULL,
  Forgalmi_engedely_szama VARCHAR(255) DEFAULT NULL,
  Rendszam VARCHAR(255) DEFAULT NULL,
  Gepjarmu_gyartmany VARCHAR(255) DEFAULT NULL,
  Gepjarmu_tipus VARCHAR(255) DEFAULT NULL,
  Oktathato_kategoria INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `oktatok`
--
CREATE TABLE oktatok (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Vezeteknev VARCHAR(255) DEFAULT NULL,
  Keresztnev VARCHAR(255) DEFAULT NULL,
  Harmadiknev VARCHAR(255) DEFAULT NULL,
  Anyja_neve VARCHAR(255) DEFAULT NULL,
  Szuletesi_orszag VARCHAR(255) DEFAULT NULL,
  Szuletesi_hely VARCHAR(255) DEFAULT NULL,
  Szuletesi_ido DATE DEFAULT NULL,
  Allampolgarsag VARCHAR(255) DEFAULT NULL,
  Lakcim_irsz INT(11) DEFAULT NULL,
  Lakcim_telepules VARCHAR(255) DEFAULT NULL,
  Lakcim_utca VARCHAR(255) DEFAULT NULL,
  Lakcim_hazszam INT(11) DEFAULT NULL,
  Lakcim_egyeb VARCHAR(255) DEFAULT NULL,
  Email VARCHAR(50) DEFAULT NULL,
  Telefonszam VARCHAR(255) DEFAULT NULL,
  Szemelyiigazolvany_szama VARCHAR(255) DEFAULT NULL,
  Jogositvany_szama VARCHAR(255) DEFAULT NULL,
  Oktato_azonosito INT(11) DEFAULT NULL,
  Oktato_jarmu INT(11) DEFAULT NULL,
  Oktatott_kategoria INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `kategoriak`
--
CREATE TABLE kategoriak (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Kategoria VARCHAR(6) DEFAULT NULL,
  Elmeleti_oraszam INT(11) DEFAULT NULL,
  Gyakorlati_oraszam INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `gyakorlati_oraszamok`
--
CREATE TABLE gyakorlati_oraszamok (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Kategoria_ID INT(11) DEFAULT NULL,
  A INT(11) DEFAULT NULL,
  Fv INT(11) DEFAULT NULL,
  Fo INT(11) DEFAULT NULL,
  Fh INT(11) DEFAULT NULL,
  Fe INT(11) DEFAULT NULL,
  Fk INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `elmeleti_oraszamok`
--
CREATE TABLE elmeleti_oraszamok (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Kategoria_id INT(11) DEFAULT NULL,
  K INT(11) DEFAULT NULL,
  Je INT(11) DEFAULT NULL,
  SZu INT(11) DEFAULT NULL,
  Bu INT(11) DEFAULT NULL,
  Mu INT(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table tanulok
--
-- Table autosiskola.tanulok does not contain any data (it is empty)

-- 
-- Dumping data for table oktato_jarmuvek
--
-- Table autosiskola.oktato_jarmuvek does not contain any data (it is empty)

-- 
-- Dumping data for table oktatok
--
-- Table autosiskola.oktatok does not contain any data (it is empty)

-- 
-- Dumping data for table kategoriak
--
-- Table autosiskola.kategoriak does not contain any data (it is empty)

-- 
-- Dumping data for table gyakorlati_oraszamok
--
-- Table autosiskola.gyakorlati_oraszamok does not contain any data (it is empty)

-- 
-- Dumping data for table elmeleti_oraszamok
--
-- Table autosiskola.elmeleti_oraszamok does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;